- name: Get groups for user '{{ user }}'
  command: "groups {{ user }}"
  register: current_groups
  changed_when: false

- name: Revoke 'sudo' for '{{ user }}'
  user:
    name: "{{ user }}"
    groups: "{{ current_groups.stdout | replace(user + ' : ', '') | replace('sudo', '') | split }}"
    append: no
