---
- name: Prepare
  hosts: all
  tasks:
    - name: "Prepare user group"
      group:
        name: "{{ linux_accounts_group }}"
        state: present

    - name: "Create user account to be deleted"
      user:
        name: "{{ item }}"
        shell: "/bin/bash"
        groups: "{{ linux_accounts_group }}"
        append: yes
      loop:
        - "charlie"
        - "dave"
