---
- name: Verify
  hosts: all
  tasks:
    - name: Check authorized key 1 for Bob
      lineinfile:
        dest: /home/bob/.ssh/authorized_keys
        line: bobssshkey1
      check_mode: true
      register: presence
      failed_when: presence.changed

    - name: Check authorized key 2 for Bob
      lineinfile:
        dest: /home/bob/.ssh/authorized_keys
        line: bobssshkey2
      check_mode: true
      register: presence
      failed_when: presence.changed

    - name: Check authorized key for Alice
      lineinfile:
        dest: /home/alice/.ssh/authorized_keys
        line: alicessshkey
      check_mode: true
      register: presence
      failed_when: presence.changed

    - name: Get group informations
      ansible.builtin.getent:
        database: group
        split: ':'
    
    - name: Check sudo permissions
      assert:
        that:
          - "'alice' not in (ansible_facts.getent_group['sudo'][2] | split(','))"
          - "'bob' in (ansible_facts.getent_group['sudo'][2] | split(','))"
